### ISSUE TITLE
File metadata - saving edits

### ISSUE THREAD

**Issue by sharonmleon** [omeka/plugin-PBCore2#1]
If one has created an item, and then gone back to edit the pbcore metadata, things work fine if you save the metadata before moving on to edit the file metadata. If you save from the edit interface for the file metadata, then the pbcore metadata changes will be lost. 

There might not be any way around this. If that's the case we need to be really specific in the documentation about item creation and item editing needing to be a two step process: pbcore metadata and file metadata separately.

**Comment by zerocrates** [comment]
You mean like, filling in the edit form for the item, and then instead of saving it clicking the link to edit a file's metadata? That's a new tab open, though. I'm not sure the situation where you can lose metadata that you're encountering.

**Comment by sharonmleon** [comment]
Yep. Totally user error. Closing
